- hosts: opscenter_server
  user: root
  
  roles:
    - cassandra_common
    - cassandra_opscenter
 
- hosts: cassandra_servers
  user: root
 
  roles:
    - cassandra_common
    - cassandra_agent
    
